

# command to install dependecies



env:
  global:
  - CC_TEST_REPORTER_ID=6d3379169de0e2a1a780f93c8f0545849b6227531f6f891b3da576b1ff24624c

language: python
python: "3.6"


install:
    - pip install -r requirements.txt
    - pip install git+https://github.com/chibisov/drf-extensions.git@master
    - pip install git+https://github.com/django-extensions/django-extensions.git@master
    

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python manage.py test
  - COVERALLS_REPO_TOKEN="hKYQcOAXuER02FSkC0jNXzmGotPpoY3Gu" coveralls

after_script:
  - coveralls
  



