language: python
python: 3.7
dist: xenial
sudo: true

# command to install dependecies

install:
    - pip install -r requirements.txt

script: coverage run manage.py test

env:
  global:
    - CC_TEST_REPORTER_ID=6d3379169de0e2a1a780f93c8f0545849b6227531f6f891b3da576b1ff24624c



