# Generated by Django 2.1 on 2018-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181009_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default='https://www.planwallpaper.com/static/images/nature_backgrounds_amazing_background_cover_7052.jpg'),
        ),
    ]
