# Generated by Django 2.1 on 2018-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181009_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated from the title of the article', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated from the name of the category', max_length=200, unique=True),
        ),
    ]
